### ISSUE TITLE
jiggle physics magically stopped working properly (semi-fixed now?)

### ISSUE THREAD

**Issue by alexanderloverde** [detomon/wigglebone#10]
### Godot version

v4.2.2.stable.official

### Issue description

https://github.com/detomon/wigglebone/assets/36207658/3181f4ff-12b8-4837-a255-62cff465bbcf

above is a video showing the issue, whenever the character moves the wigglebones seem to clip into her as she moves around instead of jiggling like normal (and this applies to all characters with wigglebones), i have zero clue what caused this and have exhausted pretty much all possibilities like changing the physics settings and deleting physical bones (both didn't work)

weirdest thing is that i reverted to an older version of the project where theoretically this didn't happen and this still happened???? i have no clue what to do and think that wigglebone just magically stopped working or my game project is haunted

https://github.com/detomon/wigglebone/assets/36207658/97822eab-d147-4bdc-9121-359aa6bb1baf

here's a reference video from back when it did work properly

### Steps to reproduce

i have no idea to be honest

**Comment by alexanderloverde** [comment]
after looking through the GitHub it looks like there was a recent update last week, that's around the time I noticed this happening so maybe that caused it somehow? still new to godot, do add-ons from assetlib automatically update?

**Comment by JekSun97** [comment]
Sorry for being off topic. But when I saw this plugin, I was sure that this plugin was needed only for these same bones :D

**Comment by alexanderloverde** [comment]
i ended up reinstalling the addon from assetlib and it seems to work properly now? i didn't make any changes from that so I'm going to leave this up and will let the dev decide if it's fixed in case someone else runs into this issue

**Comment by detomon** [comment]
Not sure what happened there. Maybe an accidental code change in one of the plugin scripts? Addons from the asset library do not update themselves automatically. I did push changes to a development branch last week, but this doesn't influence the current version.

You said, that you reverted to an older version of the project. Are you using Git for the project or was it from a backup? In case of Git, maybe you can find the local change which created this issue (code change, project setting, etc.). It's not impossible, that some setting is the culprit, which would be interesting to know.

**Comment by alexanderloverde** [comment]
I don't think I messed with any of the addon files prior to their problem occurring? Initially thought it was because I switched over to the Jolt physics engine or because I added physical bones for ragdolls, nothing I changed worked

When I reverted to an older version of the project I just downloaded one of the builds from a few weeks ago and opened it as a separate project and issue was still there which is baffling

It's fixed now and the addon works fine so I'll probably close this, still have no idea what caused this and no idea what fixed it so I'm going to assume it's voodoo witchcraft

**Comment by alexanderloverde** [comment]
alright nevermind, i guess it just un-fixed itself somehow

https://github.com/detomon/wigglebone/assets/36207658/e782d8fb-cad7-4f0f-89ab-05a2f43d82b5

i made no changes. i literally made no changes and it's back. really starting to annoy me because this is a really cool addon and i have no way to recreate it to fix it

only other thing i could possibly think of is that I'm using multiplayer nodes like multiplayersynchronizer, but those have been in there for a while as well so i don't know if that's the issue either

**Comment by alexanderloverde** [comment]
this is probably a better visualization, the little robot uses a jiggle bone to snap back to it's original position but now whenever it moves it's snaps forward in the direction the player is moving, which it didn't do before
https://github.com/detomon/wigglebone/assets/36207658/636cbc05-ea89-48f5-a653-229118909408

**Comment by alexanderloverde** [comment]
also tried reinstalling the addon from assetlib again and it still persists, so I'm back to square one at figuring out the issue

**Comment by geegaz** [comment]
This just happened to me as well. I moved the project to Godot 4.3 without issue, but after cloning it on a new PC it broke there.
Tried: 
- restarting the project
- disabling / re-enabling the addon
- deleting the .godot folder

Before:
https://github.com/user-attachments/assets/9a2f0ebf-6789-4276-84f7-f769c3a29cfb

After:
https://github.com/user-attachments/assets/b3d7735c-9de6-4ec8-9bee-7c2a7ec1ea3b

**Comment by detomon** [comment]
The latest release is a complete rewrite (see [release notes](https://github.com/detomon/wigglebone/discussions/15)) and adds new nodes which should not have any frame rate issues. The new version requires Godot 4.3 but a fallback implementation for Godot 4.2 can be found in the [godot-4.2](https://github.com/detomon/wigglebone/tree/godot-4.2) branch.
