### ISSUE TITLE
wigglebone stops working in Godot 4.3

### ISSUE THREAD

**Issue by alexanderloverde** [detomon/wigglebone#11]
### Godot version

v4.3

### Issue description

recently updated to godot 4.3 and everything just kinda goes wonky

fish girl's tail becomes a zig zag

![image](https://github.com/user-attachments/assets/76b90c96-4a95-488b-8410-2b574da66973)

this girl's bones just completely collapsed

![image](https://github.com/user-attachments/assets/06653192-baec-4d33-8b0c-967334aa2eec)

her boobs and hair just turn her into an eldritch monstrosity

![image](https://github.com/user-attachments/assets/26041baf-09f9-4124-87dc-a1e8bb0cf825)

idk what causes this, it seems to suddenly affect other bones? scared to open up any other characters that use wigglebone to avoid any corruption

### Steps to reproduce

open up a project that uses wigglebone addon in godot 4.3

**Comment by detomon** [comment]
In the first image, it looks like the mode of the tail bone is set to "Dislocation" (the red sphere), so it gets pulled down depending on the properties. I think it should be "Rotation". Can you try to change that? Maybe it's the same for the other cases.

![Rotation](https://github.com/user-attachments/assets/0255ada1-9c7b-4049-b10c-1fc43f6c0dad)

You can also try to reset the bone poses of the skeleton. Wrong poses can happen if something changed to the bone structure.

![Reset](https://github.com/user-attachments/assets/a1251edf-0254-458c-b8ae-a79252b9d64a)

**Comment by alexanderloverde** [comment]
I intentionally used dislocation instead of rotation since I liked how that looked better, these were working perfectly fine until I updated godot to the latest version

Whenever I run the game the bones seems to endlessly shift in one direction which didn't happen previously either, at first I thought it was a problem with Jolt so I updated that but that wasn't the problem

I could try resetting the bone poses/deleting all of the wigglebones and starting over from scratch to see if that fixes it
