### ISSUE TITLE
,,,

### ISSUE THREAD

**Issue by stickylab** [detomon/wigglebone#3]
![image](https://github.com/detomon/wigglebone/assets/87752832/f638f55e-e959-4de9-8c9c-bf19366118d5)

**Comment by detomon** [comment]
Please provide some more details:

- The Godot version your are using
- The plugin version; did you install the plugin from the AssetLib or from GitHub?
- And most importantly, errors from the **Output** console (screenshot or text) when activating the plugin

**Comment by stickylab** [comment]
hey man ,, i dont even know how to implement it to my project ,can you make step by step tutorial ,,
![image](https://github.com/detomon/wigglebone/assets/87752832/3f3d1d5e-a346-418a-bf2b-8b241a155012)
i wanto add wiggly hair ,,,,,,,,,,,,,,,,

i used 3. godouw

**Comment by stickylab** [comment]
the error is not appear in godouw 3...........

**Comment by stickylab** [comment]
and How to set the degree of flexibility

**Comment by stickylab** [comment]
![image](https://github.com/detomon/wigglebone/assets/87752832/5ab665f4-bbf8-4f8a-9c68-8bc9c5b3ee51)
i hope there are some setting that i can set here ,,,,,,,,,,,,,,,,,,,,,,,,,should i set it by script ? but how to do ,,,,,,,,,,,,,,,,,,,,,,,

**Comment by detomon** [comment]
You can change the behavior in the `Properties` field: Open the resource by clicking on `chain.tres`. The important values are `Stiffness` and `Damping`. Generally, the lower the values, the more it wiggles. You have to experiment which values work for your use case. Also `Length` should roughly by as long as the bone you are animating.

You can limit the "degree of flexibility" (if it's that, what you mean) with `Max Degrees`. A similar effect can sometimes also be achieve by using higher values for `Stiffness` and/or `Damping` and may look better.

She same `Properties` resource can be used for multiple bones if they should have the same behavior.
