### ISSUE TITLE
Please add or link a getting started guide

### ISSUE THREAD

**Issue by AbrahamBrookes** [detomon/wigglebone#4]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### Issue description

How do I install and use this plugin? I checked out the git repo and copied the addon files to my godot and restarted godot but I can't find "wiggle" anywhere? Can you add a getting started guide to the readme?

### Steps to reproduce

attempt to use the addon. Notice there are no instructions about how to install and get started.

**Comment by AbrahamBrookes** [comment]
For anyone else who, like me, is a _little new_ to godot, you need to clone this git repo into a random folder `git clone git@github.com:detomon/wigglebone.git` then copy the `wigglebone/addons/wigglebones` folder to your `res://addons` folder, then restart godot and go to Project > Project Settings, then on the "Addons" tab, click "enable" next to the addon in the list.

**Comment by detomon** [comment]
Thanks for the heads-up, this is of course not self-explanatory for beginners. The README now has a installation section. I also forgot to mention that the plugin is available via the `AssetLib` editor tab.

In some circumstances, resources can't be loaded properly when adding a new plugin (errors in the console). As you mentioned, reloading the project will fix it. This seems to be a quirk of the editor itself. It shouldn't happen usually, but I can't do much about that, unfortunately.
