### ISSUE TITLE
Chain does not seem to work correctly and is very stiff

### ISSUE THREAD

**Issue by Mikeysax** [detomon/wigglebone#5]
### Godot version

4.2-beta2

### Issue description

I've added a few wiggle bones in an attempt to make the cape move but it's very stiff and the mesh doesn't seem to follow.

Any thoughts on this? I tried a bunch of different settings without much luck.

I've tried with and without external skeleton as well and override pose

### Steps to reproduce

External skeleton:

https://github.com/detomon/wigglebone/assets/15805689/8b1c35e8-a347-4d54-8c5a-57dbefff2fdf

![image](https://github.com/detomon/wigglebone/assets/15805689/8f4418e4-5f03-4942-9cc6-65eb18ef3424)

Not external skeleton:

https://github.com/detomon/wigglebone/assets/15805689/bec19fd9-5f5e-4f2a-a29f-02593d3e4075

![image](https://github.com/detomon/wigglebone/assets/15805689/5490d391-0c65-4ecf-9a2a-8f152b9f4605)

**Comment by detomon** [comment]
It looks like the cape model isn't rigged correctly. The lower part of the mesh doesn't seems to be bound properly to the corresponding bones (only the top ones). Did you create the model? In Blender, you can assign the bone weights automatically to the mesh when parenting it to the armature, which should probably do what you want.
