### ISSUE TITLE
Function argument variable name matches variable name in class

### ISSUE THREAD

**Issue by lleblanc42** [detomon/wigglebone#8]
### Godot version

v4.1.3.stable

### Issue description

The argument for he function accelerate in wiggle_bone.gd on line 270 uses the same variable name ('a') as what already exists within the class. Renaming the variable for the function argument would resolve the warning.

### Steps to reproduce

Install and enable the plugin into Godot 4.1.3, include the node on a skeleton and start the game. Game runs, but warnings are thrown.

**Comment by lleblanc42** [comment]
@detomon When can I expect a new version tag to be created with the patches?

**Comment by detomon** [comment]
Done: v2.0.2
