### ISSUE TITLE
Having trouble.. (With a skeleton/mesh.)

### ISSUE THREAD

**Issue by TheRealFame** [detomon/wigglebone#9]
### Godot version

v4.2.2 Stable

### Issue description

Hello! I'm currently having big trouble trying to implant a jiggling tail with the addon. As I can't figure out how to push the tail down, So it just keeps a singular position, But can move remain moving forward and back, As well as

I'm having trouble giving it the ability to make it move left and right! (the gif linked will show the jigglebones addon being used, Which allowed this stuff.)

https://github.com/detomon/wigglebone/assets/29516927/a4bed1ed-cfdf-4f77-8ac8-4966ed61ed62

### Steps to reproduce

(Currently, My best advice is telling you to find a low poly model on Sketchfab, And ensure it has proper rigging for its tail. Before doing this!)

**Comment by detomon** [comment]
Are you using the "Use Gravity" option of the JiggleBones addon shown in the example video? If so, this is not really supported by WiggleBone at the moment (i.e. free hanging bones). But a similar functionality is planned for a future iteration.

**Comment by TheRealFame** [comment]
Yes. I am using the use gravity 😅, So I'll wait out functionality for it here

**Comment by detomon** [comment]
The latest release now supports free-hanging bones (see [release notes](https://github.com/detomon/wigglebone/discussions/15) and [this example](https://github.com/detomon/wigglebone/blob/master/examples/wigglebone/rotation/rotation_hang.tscn)). It requires Godot 4.3 but a fallback implementation for Godot 4.2 can be found in the [godot-4.2](https://github.com/detomon/wigglebone/tree/godot-4.2) branch.
